"use client";

import {
  Box,
  Button,
  Center,
  Collapse,
  Flex,
  Heading,
  Stack,
  Text,
} from "@chakra-ui/react";
import { useState } from "react";
import { PlusIcon } from "../../icons/plusIcon";
import MinusIcon from "../../icons/minusIcon";

export default function QuestionListMobile({ mt }: { mt: string }) {
  const [collapseList, setCollapseList] = useState([
    {
      id: 0,
      isShow: false,
      question: "Are there any limits on the use of ads made with TopviewAI?",
      answer:
        "You own all of your creatives, even after your plan ends. You use them in any channel without limitations. All of the stock footage used in Topview is royalty-free",
    },
    {
      id: 1,
      isShow: false,
      question: "What type of product links does TopviewAI support?",
      answer:
        "TopviewAI supports a wide range of product links, including but not limited to physical products, digital products, services, and more.",
    },
    {
      id: 2,
      isShow: false,
      question: "Can I edit the video generated by TopviewAI?",
      answer:
        "Yes, you can edit the video generated by TopviewAI to further customize it to suit your needs and preferences.",
    },
    {
      id: 3,
      isShow: false,
      question: "What type of media can I upload?",
      answer:
        "You can upload various types of media to TopviewAI, including images, videos, and audio files, to create engaging and personalized ads.",
    },
  ]);
  return (
    <Box mt={mt}>
      <Center>
        <Heading
          as="h2"
          w="21.25rem"
          h="5.5rem"
          textAlign="center"
          fontFamily="Gilroy"
          fontSize="2.5rem"
          fontWeight="700"
          lineHeight="2.71rem"
        >
          Frequently asked questions
        </Heading>
      </Center>
      <Stack spacing="16px">
        {collapseList.map((c) => (
          <Box
            key={c.id}
            borderRadius="10px"
            bg="#1F1F24"
            mt={c.id === 0 ? "1rem" : undefined}
            padding="1rem"
          >
            <Flex justifyContent="space-between" alignItems="center" h="100%">
              <Heading
                fontFamily="Eina03-SemiBold"
                fontWeight="900"
                fontSize="1.1rem"
                lineHeight="1.875rem"
              >
                {c.question}
              </Heading>
              <Button
                padding="0"
                bg="#1F1F24"
                onClick={() => {
                  const copyCollapseList = [...collapseList];
                  copyCollapseList[c.id] = { ...c, isShow: !c.isShow };

                  setCollapseList(copyCollapseList);
                }}
                display="flex"
                justifyContent="center"
                alignItems="center"
              >
                {c.isShow ? <MinusIcon /> : <PlusIcon />}
              </Button>
            </Flex>
            <Collapse startingHeight={0} in={c.isShow}>
              <Text
                color="#8E8BAE"
                fontFamily="Gilory"
                fontSize="1rem"
                lineHeight="19.34px"
                fontWeight="600"
                mt="1rem"
              >
                {c.answer}
              </Text>
            </Collapse>
          </Box>
        ))}
      </Stack>
    </Box>
  );
}
