import { Center, Stack } from "@chakra-ui/react";
import CardList from "./(components)/card/cardList";
import QuestionList from "./(components)/question/questionList";
import Body from "./(components)/body/body";
import VideoWall from "./(components)/videoWall";
import SmallCardContainerWhite from "./(components)/card/smallCardContainerWhite";
import SmallCardContainerBlack from "./(components)/card/smallCardContainerBlack";
import useSchemaScripts from "./config";
import HeroSection from "./(components)/hero/HeroSection";
import VideoCarousel from "./(components)/hero/VideoCarousel";
import TemplateSection from "./(components)/hero/TemplateSection";
import TrustedBy from "./(components)/hero/TrustedBy";

export const metadata = {
  title: "AI Video Editor |  Create viral videos with GPT-4o + Ads library",
  description:
    "Topview is an online AI video editor that turns your links or media assets into viral videos in one click, empowered by Youtube & Tiktok & Facebook ads library, best editor to create, edit, and enhance videos using AI.",
  keywords:
    "free AI video editor, AI video editor, best AI video editor, AI video editor online, Online AI video editor free, AI editor video, video editor AI, free AI video generator, AI video generator, best AI video generator, AI video generator online, Online AI video generator free, AI editor generator,  video generator AI.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
  const questionList = [
    {
      id: 0,
      isShow: false,
      question: "Are there any limits on the use of ads made with TopviewAI?",
      answer:
        "You own all of your creatives, even after your plan ends. You can use them in any channel without limitations. All of the stock footage used in Topview is royalty-free.",
    },
    {
      id: 1,
      isShow: false,
      question: "What type of product links does TopviewAI support?",
      answer:
        "TopviewAI supports a wide range of product links, including but not limited to physical products, digital products, services, and more.",
    },
    {
      id: 2,
      isShow: false,
      question: "Can I edit the video generated by TopviewAI ?",
      answer:
        "You own all of your creatives, even after your plan ends. You can use them in any channel without limitations. All of the stock footage used in Topview is royalty-free.",
    },
    {
      id: 3,
      isShow: false,
      question: "What type of media can I upload?",
      answer:
        "You can upload various types of media to TopviewAI, including images, videos, and audio files, to create engaging and personalized ads.",
    },
  ];
  const { schemaHome } = useSchemaScripts();
  return (
    <>
      <script
        id="schema-code-home"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: schemaHome }}
        defer
      />
      {/*   1.中间：文本 + 视频 */}
      <section className="flex flex-col gap-0">
        <HeroSection />
        <VideoCarousel />
        <TrustedBy />
        <div className="flex flex-col gap-[48px]">
          <TemplateSection />
          <TemplateSection title="Avatar 4" showTabs={true} cardType="avatar" />
          <TemplateSection title="Product Avatar" showTabs={true} cardType="avatar" />
        </div>
      </section>
    </>
  );
}
